fix: allow to push single items in arrays
arthurfiorette/prisma-json-types-generator pull request #182
Opened 2023-10-24 21:23 UTC by Yarmeli

Implemented a fix for #181

2023-10-25 00:52 UTC, arthurfiorette commented
Can you add some tests?

2023-10-31 21:22 UTC, Yarmeli commented
I added some tests, let me know your thoughts on them 😄 

Also, I noticed that some tests that should fail, don't really fail, for example:

```ts
// literal.test-d.ts

expectAssignable<Model>({
  id: 0,
  simple: 1,
  optional: 2,
  list: [3]
}); // ✅ it passes correctly

// copy the above code and replace the method with 'expectNotAssignable'
expectNotAssignable<Model>({
  id: 0,
  simple: 1,
  optional: 2,
  list: [3]
}); // ❌ the test passes but it should fail because this can be assigned to Model
```

My understanding is that this happens because of how arrays are handled in the `tsd` package. I [opened an issue in there](https://github.com/tsdjs/tsd/issues/199)

2023-11-01 15:02 UTC, arthurfiorette commented
Should we wait for this fix at tsd?

2023-11-01 16:19 UTC, Yarmeli commented
I don't think it would make much of a difference waiting for the tsd fix/suggestion on how to handle arrays since that currently affects new and old tests.

I can open a new issue to improve the tests depending on what the fix is for that issue

2023-11-01 16:27 UTC, arthurfiorette commented
@Yarmeli ok. CI is still failing

2023-11-01 16:28 UTC, arthurfiorette approved these changes

2023-11-01 16:30 UTC, arthurfiorette requested changes

2023-11-01 16:30 UTC, arthurfiorette commented on test/types/mongo.test-d.ts
> +expectAssignable<UpdateManyInput<Model["list"][0]>>({
```suggestion
expectAssignable<UpdateManyInput<Model["list"][number]>>({
```
Please change on other places too

2023-11-01 16:30 UTC, arthurfiorette commented on assets/namespace.d.ts
> +  push?: S[] | S;
```suggestion
  push?: S | S[];
```

consistency :)

2023-11-01 16:30 UTC, arthurfiorette commented on assets/namespace.d.ts
> +export type UpdateManyInput<T> = T | T[] | { set?: T[]; push?: T[] | T };
```suggestion
export type UpdateManyInput<T> = T | T[] | { set?: T[]; push?: T | T[] };
```

consistency :)

2023-11-01 16:42 UTC, Yarmeli commented on test/types/mongo.test-d.ts
> +expectAssignable<UpdateManyInput<Model["list"][0]>>({
Done

2023-11-01 17:59 UTC, arthurfiorette commented
Can you run `pnpm prettier --write .` and commit the changes

2023-11-01 18:05 UTC, Yarmeli commented
Hopefully, this should have worked 🤞

I am having issues on my local machine with prettier not being able to find prettier plugin modules for this repo 😞

2023-11-01 18:09 UTC, arthurfiorette approved these changes

2023-11-01 18:42 UTC, merged

2023-11-17 09:33 UTC, mrazauskas commented
@Yarmeli Just a quick note. Might be you saw already, last week I released TSTyche, a fresh type testing tool. This is the one I promised in https://github.com/tsdjs/tsd/issues/199

Repo: https://github.com/tstyche/tstyche
Documentation: https://tstyche.org

---

Before we talked about widening of inferred types. I explained it in [documentation](https://tstyche.org/reference/expect-api#type-widening). This is how TypeScript works and that is for good reason. But with TSTyche you can avoid widening in your type tests by comparing two types:

```ts
import { expect } from "tstyche";

interface Options {
  locale?: Array<"en" | "de">;
  root?: string;
}

expect<Options>().type.toBeAssignable<{
  locale: ["en", "de"];
}>();

expect<Options>().type.toBeAssignable<{
  root: string;
}>();
```

Also with TSTyche you can test types on specific versions of TypeScript: `tstyche --target 4.8,5.0,latest`. Very useful for complex generic types. Give it a try (;